"""schedule/day str->int

Revision ID: 22beb2b2f1af
Revises: ca1bb4f2011e
Create Date: 2024-06-06 17:30:49.416526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22beb2b2f1af'
down_revision: Union[str, None] = 'ca1bb4f2011e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ### // Fuck you (Adjusted)
    op.alter_column('schedule', 'day',
               existing_type=sa.VARCHAR(),
               type_=sa.SmallInteger(),
               nullable=True,
               postgresql_using="day::smallint")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'day',
               existing_type=sa.SmallInteger(),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
