"""schedule_mode

Revision ID: 232a3f837d08
Revises: e248e354eb52
Create Date: 2024-03-07 20:40:55.203680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232a3f837d08'
down_revision: Union[str, None] = 'e248e354eb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('schedule_mode', sa.Boolean(), nullable=True))
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'schedule_mode')
    # ### end Alembic commands ###
