"""added schedule table, is_blocked column3

Revision ID: 64b1fcd267a0
Revises: 2371bc7cfaf1
Create Date: 2024-02-16 15:53:13.992010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b1fcd267a0'
down_revision: Union[str, None] = '2371bc7cfaf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('day', sa.String(), nullable=False))
    op.drop_column('schedule', 'day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'day')
    # ### end Alembic commands ###
