"""user active/max_notifs add2

Revision ID: 8be02392d500
Revises: beb02bf38503
Create Date: 2024-02-29 15:08:19.880708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be02392d500'
down_revision: Union[str, None] = 'beb02bf38503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_notifs', sa.Integer(), nullable=False))
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'max_notifs')
    # ### end Alembic commands ###
