"""user schedule_time

Revision ID: a655a1e4f745
Revises: a6e65e1c676b
Create Date: 2024-03-01 10:22:24.482669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a655a1e4f745'
down_revision: Union[str, None] = 'a6e65e1c676b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('schedule_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'schedule_time')
    # ### end Alembic commands ###
