"""user_active bool

Revision ID: beb02bf38503
Revises: 8ad9456982ac
Create Date: 2024-02-28 21:41:41.657147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb02bf38503'
down_revision: Union[str, None] = '8ad9456982ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # First, set the default value for existing rows
    # Then, add the column with nullable=False
    op.add_column('users', sa.Column('active', sa.Boolean(), default=True))
    op.execute("UPDATE users SET active = False WHERE active IS NULL")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
