version: "7.0.0"

services:
  bot:
    build: .
    command: sh -c "make migrate && python -m main"
    container_name: bot
    restart: always
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - scheduler

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA='/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - redis-data:/bitnami/redis/data
    command:
      - redis-server --requirepass ${REDIS_PASS}

  scheduler:
    build: .
    container_name: scheduler
    command: sh -c "arq scheduler.main.WorkerSettings"
    restart: always
    env_file:
      - .env
    networks:
      - app
    depends_on:
        - postgres
        - redis


networks:
  app:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  postgres-data: {}
  redis-data: {}