version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot
    restart: always
    env_file:
      - .env
    networks:
      - app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA='/var/lib/postgresql/data/pgdata'
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app
    volumes:
      - redis-data:/bitnami/redis/data
    command: /bin/sh -c redis-server "--requirepass $${REDIS_PASS:?REDIS_PASS variable is not set}"

networks:
  app:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  postgres-data: {}
  redis-data: {}