"""fix key table

Revision ID: 5520d18c9a9f
Revises: 7435d5cc7acc
Create Date: 2024-02-12 01:38:01.535554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5520d18c9a9f'
down_revision: Union[str, None] = '7435d5cc7acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('used_by', sa.BigInteger(), nullable=True))
    op.drop_column('keys', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('keys', 'used_by')
    # ### end Alembic commands ###
